version: '3.8'

services:
  app:  
    build: .
    container_name: pet-finder-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PORT: 5432
      DB_PASS: root
      DB_DATABASE: petFinder
    ports:
      - "80:80"
  db:
    image: postgres:latest
    container_name: pet-finder-db
    environment:
      POSTGRES_DB: petFinder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
