version: '3.8'

services:
  app:  
    build: .
    container_name: pet-finder-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - ${PORT}:${PORT}
  db:
    image: postgres:latest
    container_name: pet-finder-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: pg_isready -U postgres